version: "3.8"

services:
  api:
    build: .
    container_name: contact-reconciliation-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_NAME=contacts_db
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
